package College;


/**
* College/StudentSearchOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from college.idl
* 05 February 2018 13:03:16 o'clock GMT
*/

public interface StudentSearchOperations 
{
  College.Student search (int id);
  void searchByRef (College.StudentHolder student);
} // interface StudentSearchOperations
