package DateApp;

/**
* DateApp/DateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 04 February 2018 18:55:25 o'clock GMT
*/

public final class DateHolder implements org.omg.CORBA.portable.Streamable
{
  public DateApp.Date value = null;

  public DateHolder ()
  {
  }

  public DateHolder (DateApp.Date initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DateApp.DateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DateApp.DateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DateApp.DateHelper.type ();
  }

}
