package DateApp;


/**
* DateApp/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 04 February 2018 18:55:25 o'clock GMT
*/

public interface Date extends DateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Date
