package College;

/**
* College/StudentSearchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from college.idl
* 05 February 2018 13:03:16 o'clock GMT
*/

public final class StudentSearchHolder implements org.omg.CORBA.portable.Streamable
{
  public College.StudentSearch value = null;

  public StudentSearchHolder ()
  {
  }

  public StudentSearchHolder (College.StudentSearch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = College.StudentSearchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    College.StudentSearchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return College.StudentSearchHelper.type ();
  }

}
