package TestApp;


/**
* TestApp/testHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test.idl
* 05 March 2018 16:53:26 o'clock GMT
*/

abstract public class testHelper
{
  private static String  _id = "IDL:TestApp/test:1.0";

  public static void insert (org.omg.CORBA.Any a, TestApp.test that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TestApp.test extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TestApp.testHelper.id (), "test");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TestApp.test read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_testStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TestApp.test value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TestApp.test narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestApp.test)
      return (TestApp.test)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestApp._testStub stub = new TestApp._testStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TestApp.test unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TestApp.test)
      return (TestApp.test)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TestApp._testStub stub = new TestApp._testStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
