package TestApp;


/**
* TestApp/testOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test.idl
* 05 March 2018 16:53:26 o'clock GMT
*/

public interface testOperations 
{
  String sayHello (String message);
} // interface testOperations
