package TestApp;

/**
* TestApp/testHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test.idl
* 05 March 2018 16:53:26 o'clock GMT
*/

public final class testHolder implements org.omg.CORBA.portable.Streamable
{
  public TestApp.test value = null;

  public testHolder ()
  {
  }

  public testHolder (TestApp.test initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestApp.testHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestApp.testHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestApp.testHelper.type ();
  }

}
