package TestApp;


/**
* TestApp/test.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from test.idl
* 05 March 2018 16:53:26 o'clock GMT
*/

public interface test extends testOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface test
