package BookShop;


/**
* BookShop/_BookSearchStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public class _BookSearchStub extends org.omg.CORBA.portable.ObjectImpl implements BookShop.BookSearch
{

  public BookShop.Book search (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("search", true);
                $out.write_long (id);
                $in = _invoke ($out);
                BookShop.Book $result = BookShop.BookHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return search (id        );
            } finally {
                _releaseReply ($in);
            }
  } // search

  public void searchByRef (BookShop.BookHolder book)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("searchByRef", true);
                $in = _invoke ($out);
                book.value = BookShop.BookHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                searchByRef (book        );
            } finally {
                _releaseReply ($in);
            }
  } // searchByRef

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BookShop/BookSearch:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BookSearchStub
