package BookShop;


/**
* BookShop/_BookSearchImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public abstract class _BookSearchImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements BookShop.BookSearch, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BookSearchImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("search", new java.lang.Integer (0));
    _methods.put ("searchByRef", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BookShop/BookSearch/search
       {
         int id = in.read_long ();
         BookShop.Book $result = null;
         $result = this.search (id);
         out = $rh.createReply();
         BookShop.BookHelper.write (out, $result);
         break;
       }

       case 1:  // BookShop/BookSearch/searchByRef
       {
         BookShop.BookHolder book = new BookShop.BookHolder ();
         this.searchByRef (book);
         out = $rh.createReply();
         BookShop.BookHelper.write (out, book.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BookShop/BookSearch:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BookSearchImplBase
