package BookShop;


/**
* BookShop/Book.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public final class Book implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String title = null;
  public String author = null;
  public String release = null;

  public Book ()
  {
  } // ctor

  public Book (int _id, String _title, String _author, String _release)
  {
    id = _id;
    title = _title;
    author = _author;
    release = _release;
  } // ctor

} // class Book
