package BookShop;

/**
* BookShop/BookSearchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public final class BookSearchHolder implements org.omg.CORBA.portable.Streamable
{
  public BookShop.BookSearch value = null;

  public BookSearchHolder ()
  {
  }

  public BookSearchHolder (BookShop.BookSearch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookShop.BookSearchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookShop.BookSearchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookShop.BookSearchHelper.type ();
  }

}
