package BookShop;

/**
* BookShop/BookHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public final class BookHolder implements org.omg.CORBA.portable.Streamable
{
  public BookShop.Book value = null;

  public BookHolder ()
  {
  }

  public BookHolder (BookShop.Book initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BookShop.BookHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BookShop.BookHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BookShop.BookHelper.type ();
  }

}
