package BookShop;


/**
* BookShop/BookSearchHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

abstract public class BookSearchHelper
{
  private static String  _id = "IDL:BookShop/BookSearch:1.0";

  public static void insert (org.omg.CORBA.Any a, BookShop.BookSearch that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BookShop.BookSearch extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BookShop.BookSearchHelper.id (), "BookSearch");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BookShop.BookSearch read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BookSearchStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BookShop.BookSearch value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BookShop.BookSearch narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BookShop.BookSearch)
      return (BookShop.BookSearch)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BookShop._BookSearchStub stub = new BookShop._BookSearchStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BookShop.BookSearch unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BookShop.BookSearch)
      return (BookShop.BookSearch)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BookShop._BookSearchStub stub = new BookShop._BookSearchStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
