package BookShop;


/**
* BookShop/BookSearchOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookshop.idl
* 05 March 2018 16:57:11 o'clock GMT
*/

public interface BookSearchOperations 
{
  BookShop.Book search (int id);
  void searchByRef (BookShop.BookHolder book);
} // interface BookSearchOperations
